site: Index Jekyll Theme

baseurl: "/pinnwaendchen"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

collections:
  pages:
    output: true
    permalink: /:name
    
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
#  - jekyll-sitemap

  